### ISSUE TITLE
Ethereum?

### ISSUE THREAD

**Issue by kethan** [igoradamenko/awesome-made-by-russians#16]
Where is ethereum?

**Comment by igoradamenko** [comment]
As I see contributors of the pinned repos in @ethereum aren't Russians 🤔 

https://github.com/ethereum/go-ethereum
https://github.com/ethereum/EIPs
https://github.com/ethereum/solidity
https://github.com/ethereum/remix
https://github.com/ethereum/web3.js

Would you mind to point at the correct repo which is created by Russian developer?

**Comment by kethan** [comment]
I think everybody knows vitalik buterin

**Comment by igoradamenko** [comment]
> Ethereum has an unusually long list of founders. Anthony Di Iorio wrote "Ethereum was founded by Vitalik Buterin, Myself, Charles Hoskinson, Mihai Alisie, & Amir Chetrit (the initial 5) in December 2013. Joseph Lubin, Gavin Wood, & Jeffrey Wilke were added in early 2014 as founders." 

— [Wikipedia](https://en.wikipedia.org/wiki/Ethereum#History)

Even though I proud of the fact that Vitalik was one of the founders, I think it's a bit unfair to claim Ethereum as “Russian software”. It's like to claim that Google is Russian company because Sergey Brin was born in USSR. Not quite fair.

So let's do not add it to prevent misunderstanding. 

Hope you understand.
