### ISSUE TITLE
Add Telegram clients

### ISSUE THREAD

**Issue by ai** [igoradamenko/awesome-made-by-russians#7]
Telegram clients and libraries are open sources, but I am not sure where the exact users from. Here are the most popular projects:

* [`DrKLO/Telegram` for Android](https://github.com/DrKLO/Telegram) by @DrKLO with 14K
* [`tdesktop`](https://github.com/telegramdesktop/tdesktop) by @john-preston with 12K
* [Telegram Web App](https://github.com/zhukov/webogram) by @zhukov with 2K
* [TelegramSwift](https://github.com/overtake/TelegramSwift) by @overtake with 2K
* [`td`](https://github.com/tdlib/td) by @levlam with 2K

We can put a single entry in the >10 category or put separated projects if we will be sure that authors from Russia.

**Comment by igoradamenko** [comment]
I guess it would be fair to call Telegram apps “made by Russians” due to the messenger history.

But I doubt that Telegram developers are interested in disclosing their identities. So I've the apps as a one entity but with links to all of them: https://github.com/igoradamenko/awesome-made-by-russians/commit/3b1794a7d98c04be7c4b7051ccd1aa37812d96a6

**Comment by igoradamenko** [comment]
Thanks to the idea, anyway! I've totally forgotten about Telegram.
